name: master

on:
  push:
    branches:
      - master

env:
  SCALA_VERSION: 2.12

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Scala Word Count
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: Compile
        run: sbt compile

  lint:
    runs-on: ubuntu-latest
    needs: build
    name: Code static analysis
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: Check code formatting
        run: sbt scalafmtCheckAll
      - name: Check code style
        run: sbt scalastyle

  bump:
    runs-on: ubuntu-latest
    needs: [build, lint]
    name: Set tag
    steps:
      - uses: actions/checkout@v1
      - name: GitHub tag bump
        uses: anothrNick/github-tag-action@1.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pack:
    needs: bump
    runs-on: ubuntu-latest
    name: Create package
    steps:
      - uses: actions/checkout@v1
      - name: Get git tag
        id: tag
        run: |
          echo ::set-output name=tag::"$(git describe --tags --long --dirty)"
      - uses: olafurpg/setup-scala@v5
      - name: Package
        env:
          APP_VERSION: ${{ steps.tag.outputs.tag }}
        run: sbt package
      - name: Debug
        run: ls -lthR target/scala-*
      - name: Upload jar artifact
        uses: actions/upload-artifact@v1
        with:
          name: wordcount_${{ steps.tag.outputs.tag }}.jar
          path: target/scala-$SCALA_VERSION/wordcount_${{ steps.tag.outputs.tag }}.jar
