name: pr

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Scala Word Count
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: Compile
        run: sbt compile
      - name: Package
        run: sbt package
  lint:
    runs-on: ubuntu-latest
    needs: build
    name: Code static analysis
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: Check code formatting
        run: sbt scalafmtCheckAll
      - name: Check code style
        run: sbt scalastyle
  pack:
    needs: [build, lint]
    runs-on: ubuntu-latest
    name: Create package
    steps:
      - uses: actions/checkout@v1
      - name: Get git tag
        id: tag
        run: |
          echo ::set-output name=tag::"$(git describe --tags --long --dirty)"
      - uses: olafurpg/setup-scala@v5
      - name: Package
        env:
          APP_VERSION: ${{ steps.tag.outputs.tag }}
        run: sbt package
